sudo: required

services:
  - docker

before_install:
  - docker build -t muhammedkamel/emaily -f ./server/Dockerfile ./server

script:
  - docker run muhammedkamel/emaily npm run test

notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
      - muhammed.nasef16@gmail.com

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t muhammedkamel/emaily -f ./server/Dockerfile ./server
  - docker push muhammedkamel/emaily

deploy:
  skip_cleanup: true
  provider: script
  script: echo "deployment successful...."
  on:
    branch: "master"
